fix missing octomap
fix /usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::~Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::addValue(float const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::~Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::OcTreeNode()'
/usr/bin/ld/usr/bin/ld: : /usr/local/lib64/libfcl.so.0.7/usr/local/lib64/libfcl.so.0.7: undefined reference to `: undefined reference to `octomap::Pointcloud::Pointcloud()octomap::Pointcloud::Pointcloud()'
'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::~OcTreeNode()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::addValue(float const&)'
/usr/bin/ld/usr/bin/ld: : /usr/local/lib64/libfcl.so.0.7/usr/local/lib64/libfcl.so.0.7: undefined reference to `: undefined reference to `octomap::Pointcloud::~Pointcloud()octomap::Pointcloud::~Pointcloud()'
'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::transform(octomath::Pose6D)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::OcTreeNode()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::~Pose6D()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::~Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::addValue(float const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::OcTreeNode::addValue(float const&)'
/usr/bin/ld/usr/bin/ld: : /usr/local/lib64/libfcl.so.0.7/usr/local/lib64/libfcl.so.0.7: undefined reference to `: undefined reference to `octomap::OcTreeNode::~OcTreeNode()octomap::OcTree::OcTree(double)'
'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::Pose6D(octomath::Pose6D const&)'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomath::Pose6D::inv() const'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7: undefined reference to `octomap::Pointcloud::Pointcloud()'
/usr/bin/ld: /usr/local/lib64/libfcl.so.0.7/usr/bin/ld/usr/bin/ld: : undefined reference to `: /usr/local/lib64/libfcl.so.0.7octomap::Pointcloud::transform(octomath::Pose6D)/usr/local/lib64/libfcl.so.0.7: undefined reference to `'